# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, Options):
        Options.setObjectName("Options")
        Options.resize(782, 807)
        self.centralwidget = QtWidgets.QWidget(Options)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 20, 721, 761))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName("tabWidget")
        self.Implicit_Explicit = QtWidgets.QWidget()
        self.Implicit_Explicit.setObjectName("Implicit_Explicit")
        self.InputCalculate_2 = QtWidgets.QPushButton(self.Implicit_Explicit)
        self.InputCalculate_2.setGeometry(QtCore.QRect(380, 600, 113, 32))
        self.InputCalculate_2.setObjectName("InputCalculate_2")
        self.InputSigma_2 = QtWidgets.QLineEdit(self.Implicit_Explicit)
        self.InputSigma_2.setGeometry(QtCore.QRect(340, 500, 125, 21))
        self.InputSigma_2.setObjectName("InputSigma_2")
        self.Sigma_2 = QtWidgets.QLabel(self.Implicit_Explicit)
        self.Sigma_2.setGeometry(QtCore.QRect(230, 490, 121, 41))
        self.Sigma_2.setObjectName("Sigma_2")
        self.TimeEnd_2 = QtWidgets.QLabel(self.Implicit_Explicit)
        self.TimeEnd_2.setGeometry(QtCore.QRect(190, 450, 181, 31))
        self.TimeEnd_2.setObjectName("TimeEnd_2")
        self.InputImplicitButton = QtWidgets.QRadioButton(self.Implicit_Explicit)
        self.InputImplicitButton.setGeometry(QtCore.QRect(340, 210, 69, 20))
        self.InputImplicitButton.setObjectName("InputImplicitButton")
        self.InputStockPrice_2 = QtWidgets.QLineEdit(self.Implicit_Explicit)
        self.InputStockPrice_2.setGeometry(QtCore.QRect(337, 250, 125, 21))
        self.InputStockPrice_2.setObjectName("InputStockPrice_2")
        self.YieldRate_2 = QtWidgets.QLabel(self.Implicit_Explicit)
        self.YieldRate_2.setGeometry(QtCore.QRect(200, 390, 171, 31))
        self.YieldRate_2.setObjectName("YieldRate_2")
        self.MethodLine_3 = QtWidgets.QLabel(self.Implicit_Explicit)
        self.MethodLine_3.setGeometry(QtCore.QRect(210, 170, 91, 31))
        self.MethodLine_3.setObjectName("MethodLine_3")
        self.Periods_2 = QtWidgets.QLabel(self.Implicit_Explicit)
        self.Periods_2.setGeometry(QtCore.QRect(150, 540, 251, 41))
        self.Periods_2.setObjectName("Periods_2")
        self.InputPutButton_2 = QtWidgets.QRadioButton(self.Implicit_Explicit)
        self.InputPutButton_2.setGeometry(QtCore.QRect(420, 170, 48, 20))
        self.InputPutButton_2.setObjectName("InputPutButton_2")
        self.Rate_2 = QtWidgets.QLabel(self.Implicit_Explicit)
        self.Rate_2.setGeometry(QtCore.QRect(180, 340, 201, 31))
        self.Rate_2.setObjectName("Rate_2")
        self.InputCallButton_2 = QtWidgets.QRadioButton(self.Implicit_Explicit)
        self.InputCallButton_2.setGeometry(QtCore.QRect(340, 170, 48, 20))
        self.InputCallButton_2.setObjectName("InputCallButton_2")
        self.InputStepsN_2 = QtWidgets.QLineEdit(self.Implicit_Explicit)
        self.InputStepsN_2.setGeometry(QtCore.QRect(340, 550, 125, 21))
        self.InputStepsN_2.setObjectName("InputStepsN_2")
        self.InputYieldRate_2 = QtWidgets.QLineEdit(self.Implicit_Explicit)
        self.InputYieldRate_2.setGeometry(QtCore.QRect(340, 400, 125, 21))
        self.InputYieldRate_2.setObjectName("InputYieldRate_2")
        self.InputReset_2 = QtWidgets.QPushButton(self.Implicit_Explicit)
        self.InputReset_2.setGeometry(QtCore.QRect(260, 600, 113, 32))
        self.InputReset_2.setObjectName("InputReset_2")
        self.StockPrice_2 = QtWidgets.QLabel(self.Implicit_Explicit)
        self.StockPrice_2.setGeometry(QtCore.QRect(190, 250, 181, 31))
        self.StockPrice_2.setObjectName("StockPrice_2")
        self.InputTimePeriod_2 = QtWidgets.QLineEdit(self.Implicit_Explicit)
        self.InputTimePeriod_2.setGeometry(QtCore.QRect(340, 450, 125, 21))
        self.InputTimePeriod_2.setObjectName("InputTimePeriod_2")
        self.InputExplicitButton = QtWidgets.QRadioButton(self.Implicit_Explicit)
        self.InputExplicitButton.setGeometry(QtCore.QRect(420, 210, 69, 20))
        self.InputExplicitButton.setObjectName("InputExplicitButton")
        self.Title_2 = QtWidgets.QLabel(self.Implicit_Explicit)
        self.Title_2.setGeometry(QtCore.QRect(90, 20, 601, 61))
        self.Title_2.setObjectName("Title_2")
        self.CallPrice_2 = QtWidgets.QLabel(self.Implicit_Explicit)
        self.CallPrice_2.setGeometry(QtCore.QRect(190, 640, 151, 31))
        self.CallPrice_2.setObjectName("CallPrice_2")
        self.TickerLabel_2 = QtWidgets.QLabel(self.Implicit_Explicit)
        self.TickerLabel_2.setGeometry(QtCore.QRect(250, 100, 51, 31))
        self.TickerLabel_2.setObjectName("TickerLabel_2")
        self.StrikePrice_2 = QtWidgets.QLabel(self.Implicit_Explicit)
        self.StrikePrice_2.setGeometry(QtCore.QRect(190, 290, 181, 41))
        self.StrikePrice_2.setObjectName("StrikePrice_2")
        self.OutputText_2 = QtWidgets.QLabel(self.Implicit_Explicit)
        self.OutputText_2.setGeometry(QtCore.QRect(320, 640, 171, 31))
        self.OutputText_2.setText("")
        self.OutputText_2.setObjectName("OutputText_2")
        self.MethodLine_2 = QtWidgets.QLabel(self.Implicit_Explicit)
        self.MethodLine_2.setGeometry(QtCore.QRect(242, 210, 91, 31))
        self.MethodLine_2.setObjectName("MethodLine_2")
        self.InputInterestRate_2 = QtWidgets.QLineEdit(self.Implicit_Explicit)
        self.InputInterestRate_2.setGeometry(QtCore.QRect(340, 350, 125, 21))
        self.InputInterestRate_2.setObjectName("InputInterestRate_2")
        self.InputStrikePrice_2 = QtWidgets.QLineEdit(self.Implicit_Explicit)
        self.InputStrikePrice_2.setGeometry(QtCore.QRect(340, 300, 125, 21))
        self.InputStrikePrice_2.setObjectName("InputStrikePrice_2")
        self.InputExtract_2 = QtWidgets.QPushButton(self.Implicit_Explicit)
        self.InputExtract_2.setGeometry(QtCore.QRect(340, 130, 117, 32))
        self.InputExtract_2.setObjectName("InputExtract_2")
        self.InputTicker_2 = QtWidgets.QLineEdit(self.Implicit_Explicit)
        self.InputTicker_2.setGeometry(QtCore.QRect(340, 100, 125, 21))
        self.InputTicker_2.setObjectName("InputTicker_2")
        self.tabWidget.addTab(self.Implicit_Explicit, "")
        self.Trinomial = QtWidgets.QWidget()
        self.Trinomial.setObjectName("Trinomial")
        self.InputCallButton_3 = QtWidgets.QRadioButton(self.Trinomial)
        self.InputCallButton_3.setGeometry(QtCore.QRect(340, 170, 48, 20))
        self.InputCallButton_3.setObjectName("InputCallButton_3")
        self.InputStockPrice_3 = QtWidgets.QLineEdit(self.Trinomial)
        self.InputStockPrice_3.setGeometry(QtCore.QRect(340, 210, 125, 21))
        self.InputStockPrice_3.setObjectName("InputStockPrice_3")
        self.InputStrikePrice_3 = QtWidgets.QLineEdit(self.Trinomial)
        self.InputStrikePrice_3.setGeometry(QtCore.QRect(340, 260, 125, 21))
        self.InputStrikePrice_3.setObjectName("InputStrikePrice_3")
        self.MethodLine_4 = QtWidgets.QLabel(self.Trinomial)
        self.MethodLine_4.setGeometry(QtCore.QRect(210, 170, 91, 31))
        self.MethodLine_4.setObjectName("MethodLine_4")
        self.InputReset_3 = QtWidgets.QPushButton(self.Trinomial)
        self.InputReset_3.setGeometry(QtCore.QRect(270, 560, 113, 32))
        self.InputReset_3.setObjectName("InputReset_3")
        self.InputCalculate_3 = QtWidgets.QPushButton(self.Trinomial)
        self.InputCalculate_3.setGeometry(QtCore.QRect(390, 560, 113, 32))
        self.InputCalculate_3.setObjectName("InputCalculate_3")
        self.Title_3 = QtWidgets.QLabel(self.Trinomial)
        self.Title_3.setGeometry(QtCore.QRect(80, 30, 601, 51))
        self.Title_3.setObjectName("Title_3")
        self.StockPrice_3 = QtWidgets.QLabel(self.Trinomial)
        self.StockPrice_3.setGeometry(QtCore.QRect(190, 210, 101, 31))
        self.StockPrice_3.setObjectName("StockPrice_3")
        self.InputTicker_3 = QtWidgets.QLineEdit(self.Trinomial)
        self.InputTicker_3.setGeometry(QtCore.QRect(340, 100, 125, 21))
        self.InputTicker_3.setObjectName("InputTicker_3")
        self.InputInterestRate_3 = QtWidgets.QLineEdit(self.Trinomial)
        self.InputInterestRate_3.setGeometry(QtCore.QRect(340, 310, 125, 21))
        self.InputInterestRate_3.setObjectName("InputInterestRate_3")
        self.OutputText_3 = QtWidgets.QLabel(self.Trinomial)
        self.OutputText_3.setGeometry(QtCore.QRect(310, 600, 171, 31))
        self.OutputText_3.setText("")
        self.OutputText_3.setObjectName("OutputText_3")
        self.Periods_3 = QtWidgets.QLabel(self.Trinomial)
        self.Periods_3.setGeometry(QtCore.QRect(150, 500, 251, 31))
        self.Periods_3.setObjectName("Periods_3")
        self.Rate_3 = QtWidgets.QLabel(self.Trinomial)
        self.Rate_3.setGeometry(QtCore.QRect(180, 300, 111, 41))
        self.Rate_3.setObjectName("Rate_3")
        self.Sigma_3 = QtWidgets.QLabel(self.Trinomial)
        self.Sigma_3.setGeometry(QtCore.QRect(230, 450, 111, 31))
        self.Sigma_3.setObjectName("Sigma_3")
        self.CallPrice_3 = QtWidgets.QLabel(self.Trinomial)
        self.CallPrice_3.setGeometry(QtCore.QRect(210, 600, 151, 31))
        self.CallPrice_3.setObjectName("CallPrice_3")
        self.InputSigma_3 = QtWidgets.QLineEdit(self.Trinomial)
        self.InputSigma_3.setGeometry(QtCore.QRect(340, 460, 125, 21))
        self.InputSigma_3.setObjectName("InputSigma_3")
        self.TimeEnd_3 = QtWidgets.QLabel(self.Trinomial)
        self.TimeEnd_3.setGeometry(QtCore.QRect(190, 400, 181, 31))
        self.TimeEnd_3.setObjectName("TimeEnd_3")
        self.InputExtract_3 = QtWidgets.QPushButton(self.Trinomial)
        self.InputExtract_3.setGeometry(QtCore.QRect(340, 130, 117, 32))
        self.InputExtract_3.setObjectName("InputExtract_3")
        self.StrikePrice_3 = QtWidgets.QLabel(self.Trinomial)
        self.StrikePrice_3.setGeometry(QtCore.QRect(190, 260, 111, 31))
        self.StrikePrice_3.setObjectName("StrikePrice_3")
        self.InputTimePeriod_3 = QtWidgets.QLineEdit(self.Trinomial)
        self.InputTimePeriod_3.setGeometry(QtCore.QRect(340, 410, 125, 21))
        self.InputTimePeriod_3.setObjectName("InputTimePeriod_3")
        self.InputYieldRate_3 = QtWidgets.QLineEdit(self.Trinomial)
        self.InputYieldRate_3.setGeometry(QtCore.QRect(340, 360, 125, 21))
        self.InputYieldRate_3.setObjectName("InputYieldRate_3")
        self.TickerLabel_3 = QtWidgets.QLabel(self.Trinomial)
        self.TickerLabel_3.setGeometry(QtCore.QRect(250, 100, 71, 31))
        self.TickerLabel_3.setObjectName("TickerLabel_3")
        self.InputPutButton_3 = QtWidgets.QRadioButton(self.Trinomial)
        self.InputPutButton_3.setGeometry(QtCore.QRect(420, 170, 48, 20))
        self.InputPutButton_3.setObjectName("InputPutButton_3")
        self.YieldRate_3 = QtWidgets.QLabel(self.Trinomial)
        self.YieldRate_3.setGeometry(QtCore.QRect(200, 350, 161, 31))
        self.YieldRate_3.setObjectName("YieldRate_3")
        self.InputStepsN_3 = QtWidgets.QLineEdit(self.Trinomial)
        self.InputStepsN_3.setGeometry(QtCore.QRect(340, 510, 125, 21))
        self.InputStepsN_3.setObjectName("InputStepsN_3")
        self.tabWidget.addTab(self.Trinomial, "")
        Options.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Options)
        self.statusbar.setObjectName("statusbar")
        Options.setStatusBar(self.statusbar)

        self.retranslateUi(Options)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Options)

    def retranslateUi(self, Options):
        _translate = QtCore.QCoreApplication.translate
        Options.setWindowTitle(_translate("Options", "MainWindow"))
        self.InputCalculate_2.setText(_translate("Options", "Calculate"))
        self.Sigma_2.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Sigma (σ)</span></p></body></html>"))
        self.TimeEnd_2.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Time period (T)</span></p></body></html>"))
        self.InputImplicitButton.setText(_translate("Options", "Implicit"))
        self.YieldRate_2.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Yield Rate (q)</span></p></body></html>"))
        self.MethodLine_3.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Option Type</span></p></body></html>"))
        self.Periods_2.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">No. of Time Steps (N)</span></p></body></html>"))
        self.InputPutButton_2.setText(_translate("Options", "Put"))
        self.Rate_2.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Interest Rate (r)</span></p></body></html>"))
        self.InputCallButton_2.setText(_translate("Options", "Call"))
        self.InputReset_2.setText(_translate("Options", "Reset"))
        self.StockPrice_2.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Stock Price (S)</span></p></body></html>"))
        self.InputExplicitButton.setText(_translate("Options", "Explicit"))
        self.Title_2.setText(_translate("Options", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; text-decoration: underline;\">Implicit Explicit Option Price Calculator</span></p></body></html>"))
        self.CallPrice_2.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Option Price</span></p></body></html>"))
        self.TickerLabel_2.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Ticker</span></p></body></html>"))
        self.StrikePrice_2.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Strike Price (K)</span></p></body></html>"))
        self.MethodLine_2.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Method</span></p></body></html>"))
        self.InputExtract_2.setText(_translate("Options", "Extract Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Implicit_Explicit), _translate("Options", "Implicit / Explicit"))
        self.InputCallButton_3.setText(_translate("Options", "Call"))
        self.MethodLine_4.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Option Type</span></p></body></html>"))
        self.InputReset_3.setText(_translate("Options", "Reset"))
        self.InputCalculate_3.setText(_translate("Options", "Calculate"))
        self.Title_3.setText(_translate("Options", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; text-decoration: underline;\">Trinomial Options Pricing Calculator</span></p></body></html>"))
        self.StockPrice_3.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Stock Price (S)</span></p></body></html>"))
        self.Periods_3.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">No. of Time Steps (N)</span></p></body></html>"))
        self.Rate_3.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Interest Rate (r)</span></p></body></html>"))
        self.Sigma_3.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Sigma (σ)</span></p></body></html>"))
        self.CallPrice_3.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Option Price</span></p></body></html>"))
        self.TimeEnd_3.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Time period (T)</span></p></body></html>"))
        self.InputExtract_3.setText(_translate("Options", "Extract Data"))
        self.StrikePrice_3.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Strike Price (K)</span></p></body></html>"))
        self.TickerLabel_3.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Ticker</span></p></body></html>"))
        self.InputPutButton_3.setText(_translate("Options", "Put"))
        self.YieldRate_3.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Yield Rate (q)</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Trinomial), _translate("Options", "Trinomial"))

