# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 807)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 40, 741, 701))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.InputCalculate_2 = QtWidgets.QPushButton(self.page)
        self.InputCalculate_2.setGeometry(QtCore.QRect(390, 610, 113, 32))
        self.InputCalculate_2.setObjectName("InputCalculate_2")
        self.InputTicker_2 = QtWidgets.QLineEdit(self.page)
        self.InputTicker_2.setGeometry(QtCore.QRect(350, 110, 125, 21))
        self.InputTicker_2.setObjectName("InputTicker_2")
        self.InputExtract_2 = QtWidgets.QPushButton(self.page)
        self.InputExtract_2.setGeometry(QtCore.QRect(350, 140, 117, 32))
        self.InputExtract_2.setObjectName("InputExtract_2")
        self.CallPrice_2 = QtWidgets.QLabel(self.page)
        self.CallPrice_2.setGeometry(QtCore.QRect(200, 650, 151, 31))
        self.CallPrice_2.setObjectName("CallPrice_2")
        self.OutputText_2 = QtWidgets.QLabel(self.page)
        self.OutputText_2.setGeometry(QtCore.QRect(330, 650, 171, 31))
        self.OutputText_2.setText("")
        self.OutputText_2.setObjectName("OutputText_2")
        self.InputReset_2 = QtWidgets.QPushButton(self.page)
        self.InputReset_2.setGeometry(QtCore.QRect(270, 610, 113, 32))
        self.InputReset_2.setObjectName("InputReset_2")
        self.InputTimePeriod_2 = QtWidgets.QLineEdit(self.page)
        self.InputTimePeriod_2.setGeometry(QtCore.QRect(350, 460, 125, 21))
        self.InputTimePeriod_2.setObjectName("InputTimePeriod_2")
        self.Title_2 = QtWidgets.QLabel(self.page)
        self.Title_2.setGeometry(QtCore.QRect(100, 30, 601, 61))
        self.Title_2.setObjectName("Title_2")
        self.StockPrice_2 = QtWidgets.QLabel(self.page)
        self.StockPrice_2.setGeometry(QtCore.QRect(200, 260, 181, 31))
        self.StockPrice_2.setObjectName("StockPrice_2")
        self.TimeEnd_2 = QtWidgets.QLabel(self.page)
        self.TimeEnd_2.setGeometry(QtCore.QRect(200, 460, 181, 31))
        self.TimeEnd_2.setObjectName("TimeEnd_2")
        self.MethodLine_3 = QtWidgets.QLabel(self.page)
        self.MethodLine_3.setGeometry(QtCore.QRect(220, 180, 91, 31))
        self.MethodLine_3.setObjectName("MethodLine_3")
        self.InputInterestRate_2 = QtWidgets.QLineEdit(self.page)
        self.InputInterestRate_2.setGeometry(QtCore.QRect(350, 360, 125, 21))
        self.InputInterestRate_2.setObjectName("InputInterestRate_2")
        self.InputStrikePrice_2 = QtWidgets.QLineEdit(self.page)
        self.InputStrikePrice_2.setGeometry(QtCore.QRect(350, 310, 125, 21))
        self.InputStrikePrice_2.setObjectName("InputStrikePrice_2")
        self.InputExplicitButton = QtWidgets.QRadioButton(self.page)
        self.InputExplicitButton.setGeometry(QtCore.QRect(430, 220, 69, 20))
        self.InputExplicitButton.setObjectName("InputExplicitButton")
        self.InputStockPrice_2 = QtWidgets.QLineEdit(self.page)
        self.InputStockPrice_2.setGeometry(QtCore.QRect(347, 260, 125, 21))
        self.InputStockPrice_2.setObjectName("InputStockPrice_2")
        self.TickerLabel_2 = QtWidgets.QLabel(self.page)
        self.TickerLabel_2.setGeometry(QtCore.QRect(260, 110, 51, 31))
        self.TickerLabel_2.setObjectName("TickerLabel_2")
        self.InputSigma_2 = QtWidgets.QLineEdit(self.page)
        self.InputSigma_2.setGeometry(QtCore.QRect(350, 510, 125, 21))
        self.InputSigma_2.setObjectName("InputSigma_2")
        self.Sigma_2 = QtWidgets.QLabel(self.page)
        self.Sigma_2.setGeometry(QtCore.QRect(240, 500, 121, 41))
        self.Sigma_2.setObjectName("Sigma_2")
        self.InputStepsN_2 = QtWidgets.QLineEdit(self.page)
        self.InputStepsN_2.setGeometry(QtCore.QRect(350, 560, 125, 21))
        self.InputStepsN_2.setObjectName("InputStepsN_2")
        self.InputCallButton_2 = QtWidgets.QRadioButton(self.page)
        self.InputCallButton_2.setGeometry(QtCore.QRect(350, 180, 48, 20))
        self.InputCallButton_2.setObjectName("InputCallButton_2")
        self.StrikePrice_2 = QtWidgets.QLabel(self.page)
        self.StrikePrice_2.setGeometry(QtCore.QRect(200, 300, 181, 41))
        self.StrikePrice_2.setObjectName("StrikePrice_2")
        self.MethodLine_2 = QtWidgets.QLabel(self.page)
        self.MethodLine_2.setGeometry(QtCore.QRect(252, 220, 91, 31))
        self.MethodLine_2.setObjectName("MethodLine_2")
        self.YieldRate_2 = QtWidgets.QLabel(self.page)
        self.YieldRate_2.setGeometry(QtCore.QRect(210, 400, 171, 31))
        self.YieldRate_2.setObjectName("YieldRate_2")
        self.Periods_2 = QtWidgets.QLabel(self.page)
        self.Periods_2.setGeometry(QtCore.QRect(160, 550, 251, 41))
        self.Periods_2.setObjectName("Periods_2")
        self.InputYieldRate_2 = QtWidgets.QLineEdit(self.page)
        self.InputYieldRate_2.setGeometry(QtCore.QRect(350, 410, 125, 21))
        self.InputYieldRate_2.setObjectName("InputYieldRate_2")
        self.InputPutButton_2 = QtWidgets.QRadioButton(self.page)
        self.InputPutButton_2.setGeometry(QtCore.QRect(430, 180, 48, 20))
        self.InputPutButton_2.setObjectName("InputPutButton_2")
        self.InputImplicitButton = QtWidgets.QRadioButton(self.page)
        self.InputImplicitButton.setGeometry(QtCore.QRect(350, 220, 69, 20))
        self.InputImplicitButton.setObjectName("InputImplicitButton")
        self.Rate_2 = QtWidgets.QLabel(self.page)
        self.Rate_2.setGeometry(QtCore.QRect(190, 350, 201, 31))
        self.Rate_2.setObjectName("Rate_2")
        self.stackedWidget.addWidget(self.page)
        
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.InputTicker_3 = QtWidgets.QLineEdit(self.page_2)
        self.InputTicker_3.setGeometry(QtCore.QRect(350, 110, 125, 21))
        self.InputTicker_3.setObjectName("InputTicker_3")
        self.InputCallButton_3 = QtWidgets.QRadioButton(self.page_2)
        self.InputCallButton_3.setGeometry(QtCore.QRect(350, 180, 48, 20))
        self.InputCallButton_3.setObjectName("InputCallButton_3")
        self.InputYieldRate_3 = QtWidgets.QLineEdit(self.page_2)
        self.InputYieldRate_3.setGeometry(QtCore.QRect(350, 370, 125, 21))
        self.InputYieldRate_3.setObjectName("InputYieldRate_3")
        self.InputPutButton_3 = QtWidgets.QRadioButton(self.page_2)
        self.InputPutButton_3.setGeometry(QtCore.QRect(430, 180, 48, 20))
        self.InputPutButton_3.setObjectName("InputPutButton_3")
        self.InputExtract_3 = QtWidgets.QPushButton(self.page_2)
        self.InputExtract_3.setGeometry(QtCore.QRect(350, 140, 117, 32))
        self.InputExtract_3.setObjectName("InputExtract_3")
        self.StockPrice_3 = QtWidgets.QLabel(self.page_2)
        self.StockPrice_3.setGeometry(QtCore.QRect(200, 220, 101, 31))
        self.StockPrice_3.setObjectName("StockPrice_3")
        self.MethodLine_4 = QtWidgets.QLabel(self.page_2)
        self.MethodLine_4.setGeometry(QtCore.QRect(220, 180, 91, 31))
        self.MethodLine_4.setObjectName("MethodLine_4")
        self.TickerLabel_3 = QtWidgets.QLabel(self.page_2)
        self.TickerLabel_3.setGeometry(QtCore.QRect(260, 110, 71, 31))
        self.TickerLabel_3.setObjectName("TickerLabel_3")
        self.InputTimePeriod_3 = QtWidgets.QLineEdit(self.page_2)
        self.InputTimePeriod_3.setGeometry(QtCore.QRect(350, 420, 125, 21))
        self.InputTimePeriod_3.setObjectName("InputTimePeriod_3")
        self.Sigma_3 = QtWidgets.QLabel(self.page_2)
        self.Sigma_3.setGeometry(QtCore.QRect(240, 460, 111, 31))
        self.Sigma_3.setObjectName("Sigma_3")
        self.Title_3 = QtWidgets.QLabel(self.page_2)
        self.Title_3.setGeometry(QtCore.QRect(90, 40, 601, 51))
        self.Title_3.setObjectName("Title_3")
        self.InputStepsN_3 = QtWidgets.QLineEdit(self.page_2)
        self.InputStepsN_3.setGeometry(QtCore.QRect(350, 520, 125, 21))
        self.InputStepsN_3.setObjectName("InputStepsN_3")
        self.CallPrice_3 = QtWidgets.QLabel(self.page_2)
        self.CallPrice_3.setGeometry(QtCore.QRect(220, 610, 151, 31))
        self.CallPrice_3.setObjectName("CallPrice_3")
        self.Rate_3 = QtWidgets.QLabel(self.page_2)
        self.Rate_3.setGeometry(QtCore.QRect(190, 310, 111, 41))
        self.Rate_3.setObjectName("Rate_3")
        self.InputStrikePrice_3 = QtWidgets.QLineEdit(self.page_2)
        self.InputStrikePrice_3.setGeometry(QtCore.QRect(350, 270, 125, 21))
        self.InputStrikePrice_3.setObjectName("InputStrikePrice_3")
        self.InputReset_3 = QtWidgets.QPushButton(self.page_2)
        self.InputReset_3.setGeometry(QtCore.QRect(280, 570, 113, 32))
        self.InputReset_3.setObjectName("InputReset_3")
        self.OutputText_3 = QtWidgets.QLabel(self.page_2)
        self.OutputText_3.setGeometry(QtCore.QRect(320, 610, 171, 31))
        self.OutputText_3.setText("")
        self.OutputText_3.setObjectName("OutputText_3")
        self.InputCalculate_3 = QtWidgets.QPushButton(self.page_2)
        self.InputCalculate_3.setGeometry(QtCore.QRect(400, 570, 113, 32))
        self.InputCalculate_3.setObjectName("InputCalculate_3")
        self.InputInterestRate_3 = QtWidgets.QLineEdit(self.page_2)
        self.InputInterestRate_3.setGeometry(QtCore.QRect(350, 320, 125, 21))
        self.InputInterestRate_3.setObjectName("InputInterestRate_3")
        self.YieldRate_3 = QtWidgets.QLabel(self.page_2)
        self.YieldRate_3.setGeometry(QtCore.QRect(210, 360, 161, 31))
        self.YieldRate_3.setObjectName("YieldRate_3")
        self.Periods_3 = QtWidgets.QLabel(self.page_2)
        self.Periods_3.setGeometry(QtCore.QRect(160, 510, 251, 31))
        self.Periods_3.setObjectName("Periods_3")
        self.InputSigma_3 = QtWidgets.QLineEdit(self.page_2)
        self.InputSigma_3.setGeometry(QtCore.QRect(350, 470, 125, 21))
        self.InputSigma_3.setObjectName("InputSigma_3")
        self.InputStockPrice_3 = QtWidgets.QLineEdit(self.page_2)
        self.InputStockPrice_3.setGeometry(QtCore.QRect(350, 220, 125, 21))
        self.InputStockPrice_3.setObjectName("InputStockPrice_3")
        self.StrikePrice_3 = QtWidgets.QLabel(self.page_2)
        self.StrikePrice_3.setGeometry(QtCore.QRect(200, 270, 111, 31))
        self.StrikePrice_3.setObjectName("StrikePrice_3")
        self.TimeEnd_3 = QtWidgets.QLabel(self.page_2)
        self.TimeEnd_3.setGeometry(QtCore.QRect(200, 410, 181, 31))
        self.TimeEnd_3.setObjectName("TimeEnd_3")
        self.stackedWidget.addWidget(self.page_2)
        self.Trinomial = QtWidgets.QPushButton(self.centralwidget)
        self.Trinomial.setGeometry(QtCore.QRect(10, 10, 121, 41))
        self.Trinomial.setObjectName("Trinomial")
        self.Implicit_Explicit = QtWidgets.QPushButton(self.centralwidget)
        self.Implicit_Explicit.setGeometry(QtCore.QRect(120, 10, 141, 41))
        self.Implicit_Explicit.setObjectName("Implicit_Explicit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.InputCalculate_2.setText(_translate("MainWindow", "Calculate"))
        self.InputExtract_2.setText(_translate("MainWindow", "Extract Data"))
        self.CallPrice_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Option Price</span></p></body></html>"))
        self.InputReset_2.setText(_translate("MainWindow", "Reset"))
        self.Title_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; text-decoration: underline;\">Implicit Explicit Option Price Calculator</span></p></body></html>"))
        self.StockPrice_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Stock Price (S)</span></p></body></html>"))
        self.TimeEnd_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Time period (T)</span></p></body></html>"))
        self.MethodLine_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Option Type</span></p></body></html>"))
        self.InputExplicitButton.setText(_translate("MainWindow", "Explicit"))
        self.TickerLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Ticker</span></p></body></html>"))
        self.Sigma_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Sigma (σ)</span></p></body></html>"))
        self.InputCallButton_2.setText(_translate("MainWindow", "Call"))
        self.StrikePrice_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Strike Price (K)</span></p></body></html>"))
        self.MethodLine_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Method</span></p></body></html>"))
        self.YieldRate_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Yield Rate (q)</span></p></body></html>"))
        self.Periods_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">No. of Time Steps (N)</span></p></body></html>"))
        self.InputPutButton_2.setText(_translate("MainWindow", "Put"))
        self.InputImplicitButton.setText(_translate("MainWindow", "Implicit"))
        self.Rate_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Interest Rate (r)</span></p></body></html>"))
        self.InputCallButton_3.setText(_translate("MainWindow", "Call"))
        self.InputPutButton_3.setText(_translate("MainWindow", "Put"))
        self.InputExtract_3.setText(_translate("MainWindow", "Extract Data"))
        self.StockPrice_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Stock Price (S)</span></p></body></html>"))
        self.MethodLine_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Option Type</span></p></body></html>"))
        self.TickerLabel_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Ticker</span></p></body></html>"))
        self.Sigma_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Sigma (σ)</span></p></body></html>"))
        self.Title_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; text-decoration: underline;\">Trinomial Options Pricing Calculator</span></p></body></html>"))
        self.CallPrice_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Option Price</span></p></body></html>"))
        self.Rate_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Interest Rate (r)</span></p></body></html>"))
        self.InputReset_3.setText(_translate("MainWindow", "Reset"))
        self.InputCalculate_3.setText(_translate("MainWindow", "Calculate"))
        self.YieldRate_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Yield Rate (q)</span></p></body></html>"))
        self.Periods_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">No. of Time Steps (N)</span></p></body></html>"))
        self.StrikePrice_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Strike Price (K)</span></p></body></html>"))
        self.TimeEnd_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Time period (T)</span></p></body></html>"))
        self.Trinomial.setText(_translate("MainWindow", "Trinomial"))
        self.Implicit_Explicit.setText(_translate("MainWindow", "Implicit / Explicit"))

