# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Options.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, Options):
        Options.setObjectName("Options")
        Options.resize(782, 807)
        self.centralwidget = QtWidgets.QWidget(Options)
        self.centralwidget.setObjectName("centralwidget")
        self.StockPrice = QtWidgets.QLabel(self.centralwidget)
        self.StockPrice.setGeometry(QtCore.QRect(170, 270, 104, 17))
        self.StockPrice.setObjectName("StockPrice")
        self.Sigma = QtWidgets.QLabel(self.centralwidget)
        self.Sigma.setGeometry(QtCore.QRect(210, 520, 68, 17))
        self.Sigma.setObjectName("Sigma")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(230, 50, 303, 33))
        self.Title.setObjectName("Title")
        self.YieldRate = QtWidgets.QLabel(self.centralwidget)
        self.YieldRate.setGeometry(QtCore.QRect(180, 420, 94, 17))
        self.YieldRate.setObjectName("YieldRate")
        self.MethodLine = QtWidgets.QLabel(self.centralwidget)
        self.MethodLine.setGeometry(QtCore.QRect(220, 220, 53, 17))
        self.MethodLine.setObjectName("MethodLine")
        self.Periods = QtWidgets.QLabel(self.centralwidget)
        self.Periods.setGeometry(QtCore.QRect(130, 570, 148, 17))
        self.Periods.setObjectName("Periods")
        self.StrikePrice = QtWidgets.QLabel(self.centralwidget)
        self.StrikePrice.setGeometry(QtCore.QRect(170, 320, 105, 17))
        self.StrikePrice.setObjectName("StrikePrice")
        self.TimeEnd = QtWidgets.QLabel(self.centralwidget)
        self.TimeEnd.setGeometry(QtCore.QRect(170, 470, 107, 17))
        self.TimeEnd.setObjectName("TimeEnd")
        self.CallPrice = QtWidgets.QLabel(self.centralwidget)
        self.CallPrice.setGeometry(QtCore.QRect(190, 620, 86, 17))
        self.CallPrice.setObjectName("CallPrice")
        self.TickerLabel = QtWidgets.QLabel(self.centralwidget)
        self.TickerLabel.setGeometry(QtCore.QRect(220, 130, 44, 17))
        self.TickerLabel.setObjectName("TickerLabel")
        self.Rate = QtWidgets.QLabel(self.centralwidget)
        self.Rate.setGeometry(QtCore.QRect(160, 370, 111, 17))
        self.Rate.setObjectName("Rate")
        self.InputStepsN = QtWidgets.QLineEdit(self.centralwidget)
        self.InputStepsN.setGeometry(QtCore.QRect(300, 570, 125, 21))
        self.InputStepsN.setObjectName("InputStepsN")
        self.InputCallButton = QtWidgets.QRadioButton(self.centralwidget)
        self.InputCallButton.setGeometry(QtCore.QRect(300, 620, 48, 20))
        self.InputCallButton.setObjectName("InputCallButton")
        self.InputStockPrice = QtWidgets.QLineEdit(self.centralwidget)
        self.InputStockPrice.setGeometry(QtCore.QRect(300, 270, 125, 21))
        self.InputStockPrice.setObjectName("InputStockPrice")
        self.InputTicker = QtWidgets.QLineEdit(self.centralwidget)
        self.InputTicker.setGeometry(QtCore.QRect(290, 130, 125, 21))
        self.InputTicker.setObjectName("InputTicker")
        self.InputYieldRate = QtWidgets.QLineEdit(self.centralwidget)
        self.InputYieldRate.setGeometry(QtCore.QRect(300, 420, 125, 21))
        self.InputYieldRate.setObjectName("InputYieldRate")
        self.InputExplicitButton = QtWidgets.QRadioButton(self.centralwidget)
        self.InputExplicitButton.setGeometry(QtCore.QRect(370, 220, 69, 20))
        self.InputExplicitButton.setObjectName("InputExplicitButton")
        self.InputImplicitButton = QtWidgets.QRadioButton(self.centralwidget)
        self.InputImplicitButton.setGeometry(QtCore.QRect(290, 220, 69, 20))
        self.InputImplicitButton.setObjectName("InputImplicitButton")
        self.InputExtract = QtWidgets.QPushButton(self.centralwidget)
        self.InputExtract.setGeometry(QtCore.QRect(290, 160, 117, 32))
        self.InputExtract.setObjectName("InputExtract")
        self.InputSigma = QtWidgets.QLineEdit(self.centralwidget)
        self.InputSigma.setGeometry(QtCore.QRect(300, 520, 125, 21))
        self.InputSigma.setObjectName("InputSigma")
        self.InputTimePeriod = QtWidgets.QLineEdit(self.centralwidget)
        self.InputTimePeriod.setGeometry(QtCore.QRect(300, 470, 125, 21))
        self.InputTimePeriod.setObjectName("InputTimePeriod")
        self.InputInterestRate = QtWidgets.QLineEdit(self.centralwidget)
        self.InputInterestRate.setGeometry(QtCore.QRect(300, 370, 125, 21))
        self.InputInterestRate.setObjectName("InputInterestRate")
        self.InputStrikePrice = QtWidgets.QLineEdit(self.centralwidget)
        self.InputStrikePrice.setGeometry(QtCore.QRect(300, 320, 125, 21))
        self.InputStrikePrice.setObjectName("InputStrikePrice")
        self.InputPutButton = QtWidgets.QRadioButton(self.centralwidget)
        self.InputPutButton.setGeometry(QtCore.QRect(370, 620, 48, 20))
        self.InputPutButton.setObjectName("InputPutButton")
        self.InputCalculate = QtWidgets.QPushButton(self.centralwidget)
        self.InputCalculate.setGeometry(QtCore.QRect(360, 670, 113, 32))
        self.InputCalculate.setObjectName("InputCalculate")
        self.OutputText = QtWidgets.QLabel(self.centralwidget)
        self.OutputText.setGeometry(QtCore.QRect(270, 710, 171, 31))
        self.OutputText.setText("")
        self.OutputText.setObjectName("OutputText")
        self.InputReset = QtWidgets.QPushButton(self.centralwidget)
        self.InputReset.setGeometry(QtCore.QRect(240, 670, 113, 32))
        self.InputReset.setObjectName("InputReset")
        Options.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Options)
        self.statusbar.setObjectName("statusbar")
        Options.setStatusBar(self.statusbar)

        self.retranslateUi(Options)
        QtCore.QMetaObject.connectSlotsByName(Options)

    def retranslateUi(self, Options):
        _translate = QtCore.QCoreApplication.translate
        Options.setWindowTitle(_translate("Options", "MainWindow"))
        self.StockPrice.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Stock Price (S)</span></p></body></html>"))
        self.Sigma.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Sigma (σ)</span></p></body></html>"))
        self.Title.setText(_translate("Options", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; text-decoration: underline;\">Option Price Calculator</span></p></body></html>"))
        self.YieldRate.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Yield Rate (q)</span></p></body></html>"))
        self.MethodLine.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Method</span></p></body></html>"))
        self.Periods.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">No. of Time Steps (N)</span></p></body></html>"))
        self.StrikePrice.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Strike Price (K)</span></p></body></html>"))
        self.TimeEnd.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Time period (T)</span></p></body></html>"))
        self.CallPrice.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Option Price</span></p></body></html>"))
        self.TickerLabel.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Ticker</span></p></body></html>"))
        self.Rate.setText(_translate("Options", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Interest Rate (r)</span></p></body></html>"))
        self.InputCallButton.setText(_translate("Options", "Call"))
        self.InputExplicitButton.setText(_translate("Options", "Explicit"))
        self.InputImplicitButton.setText(_translate("Options", "Implicit"))
        self.InputExtract.setText(_translate("Options", "Extract Data"))
        self.InputPutButton.setText(_translate("Options", "Put"))
        self.InputCalculate.setText(_translate("Options", "Calculate"))
        self.InputReset.setText(_translate("Options", "Reset"))

