# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'implicit.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(782, 779)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Periods = QtWidgets.QLabel(self.centralwidget)
        self.Periods.setGeometry(QtCore.QRect(170, 530, 251, 41))
        self.Periods.setObjectName("Periods")
        self.TimeEnd_2 = QtWidgets.QLabel(self.centralwidget)
        self.TimeEnd_2.setGeometry(QtCore.QRect(210, 440, 181, 31))
        self.TimeEnd_2.setObjectName("TimeEnd_2")
        self.Sigma_2 = QtWidgets.QLabel(self.centralwidget)
        self.Sigma_2.setGeometry(QtCore.QRect(250, 480, 121, 41))
        self.Sigma_2.setObjectName("Sigma_2")
        self.Rate = QtWidgets.QLabel(self.centralwidget)
        self.Rate.setGeometry(QtCore.QRect(200, 330, 201, 31))
        self.Rate.setObjectName("Rate")
        self.TickerLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.TickerLabel_2.setGeometry(QtCore.QRect(270, 130, 51, 31))
        self.TickerLabel_2.setObjectName("TickerLabel_2")
        self.Title_2 = QtWidgets.QLabel(self.centralwidget)
        self.Title_2.setGeometry(QtCore.QRect(110, 50, 601, 61))
        self.Title_2.setObjectName("Title_2")
        self.InputYieldRate = QtWidgets.QLineEdit(self.centralwidget)
        self.InputYieldRate.setGeometry(QtCore.QRect(360, 390, 125, 21))
        self.InputYieldRate.setObjectName("InputYieldRate")
        self.InputStrikePrice = QtWidgets.QLineEdit(self.centralwidget)
        self.InputStrikePrice.setGeometry(QtCore.QRect(360, 290, 125, 21))
        self.InputStrikePrice.setObjectName("InputStrikePrice")
        self.InputSigma = QtWidgets.QLineEdit(self.centralwidget)
        self.InputSigma.setGeometry(QtCore.QRect(360, 490, 125, 21))
        self.InputSigma.setObjectName("InputSigma")
        self.InputStockPrice = QtWidgets.QLineEdit(self.centralwidget)
        self.InputStockPrice.setGeometry(QtCore.QRect(357, 240, 125, 21))
        self.InputStockPrice.setObjectName("InputStockPrice")
        self.InputTicker = QtWidgets.QLineEdit(self.centralwidget)
        self.InputTicker.setGeometry(QtCore.QRect(360, 130, 125, 21))
        self.InputTicker.setObjectName("InputTicker")
        self.MethodLine = QtWidgets.QLabel(self.centralwidget)
        self.MethodLine.setGeometry(QtCore.QRect(230, 200, 91, 31))
        self.MethodLine.setObjectName("MethodLine")
        self.OutputText = QtWidgets.QLabel(self.centralwidget)
        self.OutputText.setGeometry(QtCore.QRect(340, 670, 171, 31))
        self.OutputText.setText("")
        self.OutputText.setObjectName("OutputText")
        self.InputExtract = QtWidgets.QPushButton(self.centralwidget)
        self.InputExtract.setGeometry(QtCore.QRect(360, 160, 117, 32))
        self.InputExtract.setObjectName("InputExtract")
        self.InputCalculate = QtWidgets.QPushButton(self.centralwidget)
        self.InputCalculate.setGeometry(QtCore.QRect(400, 630, 113, 32))
        self.InputCalculate.setObjectName("InputCalculate")
        self.StrikePrice_2 = QtWidgets.QLabel(self.centralwidget)
        self.StrikePrice_2.setGeometry(QtCore.QRect(210, 280, 181, 41))
        self.StrikePrice_2.setObjectName("StrikePrice_2")
        self.YieldRate_2 = QtWidgets.QLabel(self.centralwidget)
        self.YieldRate_2.setGeometry(QtCore.QRect(220, 380, 171, 31))
        self.YieldRate_2.setObjectName("YieldRate_2")
        self.StockPrice_2 = QtWidgets.QLabel(self.centralwidget)
        self.StockPrice_2.setGeometry(QtCore.QRect(210, 240, 181, 31))
        self.StockPrice_2.setObjectName("StockPrice_2")
        self.InputInterestRate = QtWidgets.QLineEdit(self.centralwidget)
        self.InputInterestRate.setGeometry(QtCore.QRect(360, 340, 125, 21))
        self.InputInterestRate.setObjectName("InputInterestRate")
        self.InputPutButton = QtWidgets.QRadioButton(self.centralwidget)
        self.InputPutButton.setGeometry(QtCore.QRect(440, 200, 48, 20))
        self.InputPutButton.setObjectName("InputPutButton")
        self.InputCallButton = QtWidgets.QRadioButton(self.centralwidget)
        self.InputCallButton.setGeometry(QtCore.QRect(360, 200, 48, 20))
        self.InputCallButton.setObjectName("InputCallButton")
        self.CallPrice = QtWidgets.QLabel(self.centralwidget)
        self.CallPrice.setGeometry(QtCore.QRect(210, 670, 151, 31))
        self.CallPrice.setObjectName("CallPrice")
        self.InputTimePeriod = QtWidgets.QLineEdit(self.centralwidget)
        self.InputTimePeriod.setGeometry(QtCore.QRect(360, 440, 125, 21))
        self.InputTimePeriod.setObjectName("InputTimePeriod")
        self.InputReset = QtWidgets.QPushButton(self.centralwidget)
        self.InputReset.setGeometry(QtCore.QRect(280, 630, 113, 32))
        self.InputReset.setObjectName("InputReset")
        self.InputStepsN = QtWidgets.QLineEdit(self.centralwidget)
        self.InputStepsN.setGeometry(QtCore.QRect(360, 540, 125, 21))
        self.InputStepsN.setObjectName("InputStepsN")
        self.InputStepsM = QtWidgets.QLineEdit(self.centralwidget)
        self.InputStepsM.setGeometry(QtCore.QRect(360, 590, 125, 21))
        self.InputStepsM.setObjectName("InputStepsM")
        self.Periods_2 = QtWidgets.QLabel(self.centralwidget)
        self.Periods_2.setGeometry(QtCore.QRect(290, 580, 31, 41))
        self.Periods_2.setObjectName("Periods_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Periods.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">No. of Time Steps (N)</span></p></body></html>"))
        self.TimeEnd_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Time period (T)</span></p></body></html>"))
        self.Sigma_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Sigma (σ)</span></p></body></html>"))
        self.Rate.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Interest Rate (r)</span></p></body></html>"))
        self.TickerLabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Ticker</span></p></body></html>"))
        self.Title_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; text-decoration: underline;\">Implicit Explicit Option Price Calculator</span></p></body></html>"))
        self.MethodLine.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Option Type</span></p></body></html>"))
        self.InputExtract.setText(_translate("MainWindow", "Extract Data"))
        self.InputCalculate.setText(_translate("MainWindow", "Calculate"))
        self.StrikePrice_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Strike Price (K)</span></p></body></html>"))
        self.YieldRate_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Yield Rate (q)</span></p></body></html>"))
        self.StockPrice_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Stock Price (S)</span></p></body></html>"))
        self.InputPutButton.setText(_translate("MainWindow", "Put"))
        self.InputCallButton.setText(_translate("MainWindow", "Call"))
        self.CallPrice.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Option Price</span></p></body></html>"))
        self.InputReset.setText(_translate("MainWindow", "Reset"))
        self.Periods_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">(M)</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

